language: node_js

before_script:
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g typescript
  - bower install
 
script: grunt test

after_success: grunt coveralls